### ISSUE TITLE
install failed, Need help

### ISSUE THREAD

**Issue by KiritoStudio** [mrcotter/mrcotter_dotfiles#2]
kirito-Sharing:mpv kirito$ ./install.sh 
Password:
Installing mpv via Homebrew
==> Downloading https://github.com/mpv-player/mpv/archive/v0.17.0.tar.gz
Already downloaded: /Users/kirito/Library/Caches/Homebrew/mpv-0.17.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
Already downloaded: /Users/kirito/Library/Caches/Homebrew/mpv--docutils-0.12.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
==> Downloading https://waf.io/waf-1.8.12
Already downloaded: /Users/kirito/Library/Caches/Homebrew/mpv--waf-1.8.12.12
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.17.0 --enable-gpl3 --
==> python3 waf install
Last 15 lines from /Users/kirito/Library/Logs/Homebrew/mpv/03.python3:
[195/201] Compiling input/keycodes.c
[196/201] Compiling osdep/path-unix.c
[197/201] Compiling video/filter/vf_dlopen.c
[198/201] Linking build/mpv
Undefined symbols for architecture x86_64:
  "_CVPixelBufferGetPixelFormatType", referenced from:
      _process_image in videotoolbox.c.14.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/private/tmp/mpv-20160606-13105-lfyjf1/mpv-0.17.0/build'
Build failed
 -> task in 'mpv' failed (exit status 1): 
    {task 4347244328: cprogram main-fn-unix.c.15.o,audio.c.14.o,audio_buffer.c.14.o,chmap.c.14.o,chmap_sel.c.14.o,fmt-conversion.c.14.o,format.c.14.o,mixer.c.14.o,ad_lavc.c.14.o,ad_spdif.c.14.o,dec_audio.c.14.o,af.c.14.o,af_channels.c.14.o,af_delay.c.14.o,af_drc.c.14.o,af_equalizer.c.14.o,af_format.c.14.o,af_lavcac3enc.c.14.o,af_lavfi.c.14.o,af_lavrresample.c.14.o,af_pan.c.14.o,af_scaletempo.c.14.o,af_volume.c.14.o,tools.c.14.o,ao.c.14.o,ao_coreaudio.c.14.o,ao_coreaudio_chmap.c.14.o,ao_coreaudio_exclusive.c.14.o,ao_coreaudio_properties.c.14.o,ao_coreaudio_utils.c.14.o,ao_null.c.14.o,ao_pcm.c.14.o,pull.c.14.o,push.c.14.o,av_common.c.14.o,av_log.c.14.o,codecs.c.14.o,common.c.14.o,tags.c.14.o,msg.c.14.o,playlist.c.14.o,version.c.14.o,codec_tags.c.14.o,cue.c.14.o,demux.c.14.o,demux_cue.c.14.o,demux_disc.c.14.o,demux_edl.c.14.o,demux_lavf.c.14.o,demux_mf.c.14.o,demux_mkv.c.14.o,demux_mkv_timeline.c.14.o,demux_null.c.14.o,demux_playlist.c.14.o,demux_raw.c.14.o,demux_rar.c.14.o,demux_timeline.c.14.o,demux_tv.c.14.o,ebml.c.14.o,packet.c.14.o,timeline.c.14.o,cmd_list.c.14.o,cmd_parse.c.14.o,event.c.14.o,input.c.14.o,ipc.c.14.o,ipc-unix.c.14.o,keycodes.c.14.o,bstr.c.14.o,charset_conv.c.14.o,dispatch.c.14.o,json.c.14.o,ring.c.14.o,rendezvous.c.14.o,m_config.c.14.o,m_option.c.14.o,m_property.c.14.o,options.c.14.o,parse_commandline.c.14.o,parse_configfile.c.14.o,path.c.14.o,audio.c.14.o,client.c.14.o,command.c.14.o,configfiles.c.14.o,external_files.c.14.o,loadfile.c.14.o,main.c.14.o,misc.c.14.o,lavfi.c.14.o,lua.c.14.o,osd.c.14.o,playloop.c.14.o,screenshot.c.14.o,scripting.c.14.o,sub.c.14.o,video.c.14.o,cache.c.14.o,cache_file.c.14.o,cookies.c.14.o,frequencies.c.14.o,rar.c.14.o,stream.c.14.o,stream_avdevice.c.14.o,stream_edl.c.14.o,stream_file.c.14.o,stream_lavf.c.14.o,stream_memory.c.14.o,stream_mf.c.14.o,stream_null.c.14.o,stream_rar.c.14.o,stream_tv.c.14.o,tv.c.14.o,tvi_dummy.c.14.o,ass_mp.c.14.o,dec_sub.c.14.o,draw_bmp.c.14.o,img_convert.c.14.o,lavc_conv.c.14.o,osd.c.14.o,osd_libass.c.14.o,sd_ass.c.14.o,sd_lavc.c.14.o,csputils.c.14.o,fmt-conversion.c.14.o,image_writer.c.14.o,img_format.c.14.o,mp_image.c.14.o,mp_image_pool.c.14.o,sws_utils.c.14.o,dec_video.c.14.o,vd_lavc.c.14.o,videotoolbox.c.14.o,vf.c.14.o,vf_buffer.c.14.o,vf_crop.c.14.o,vf_dlopen.c.14.o,vf_dsize.c.14.o,vf_eq.c.14.o,vf_expand.c.14.o,vf_flip.c.14.o,vf_format.c.14.o,vf_gradfun.c.14.o,vf_lavfi.c.14.o,vf_mirror.c.14.o,vf_noformat.c.14.o,vf_pullup.c.14.o,vf_rotate.c.14.o,vf_scale.c.14.o,vf_stereo3d.c.14.o,vf_sub.c.14.o,vf_yadif.c.14.o,aspect.c.14.o,bitmap_packer.c.14.o,dither.c.14.o,filter_kernels.c.14.o,vo.c.14.o,vo_image.c.14.o,vo_null.c.14.o,win_state.c.14.o,terminal-unix.c.14.o,io.c.14.o,timer.c.14.o,timer-darwin.c.14.o,threads.c.14.o,semaphore_osx.c.14.o,subprocess.c.14.o,subprocess-posix.c.14.o,path-unix.c.14.o,ta.c.14.o,ta_talloc.c.14.o,ta_utils.c.14.o -> mpv}
['clang', 'osdep/main-fn-unix.c.15.o', 'audio/audio.c.14.o', 'audio/audio_buffer.c.14.o', 'audio/chmap.c.14.o', 'audio/chmap_sel.c.14.o', 'audio/fmt-conversion.c.14.o', 'audio/format.c.14.o', 'audio/mixer.c.14.o', 'audio/decode/ad_lavc.c.14.o', 'audio/decode/ad_spdif.c.14.o', 'audio/decode/dec_audio.c.14.o', 'audio/filter/af.c.14.o', 'audio/filter/af_channels.c.14.o', 'audio/filter/af_delay.c.14.o', 'audio/filter/af_drc.c.14.o', 'audio/filter/af_equalizer.c.14.o', 'audio/filter/af_format.c.14.o', 'audio/filter/af_lavcac3enc.c.14.o', 'audio/filter/af_lavfi.c.14.o', 'audio/filter/af_lavrresample.c.14.o', 'audio/filter/af_pan.c.14.o', 'audio/filter/af_scaletempo.c.14.o', 'audio/filter/af_volume.c.14.o', 'audio/filter/tools.c.14.o', 'audio/out/ao.c.14.o', 'audio/out/ao_coreaudio.c.14.o', 'audio/out/ao_coreaudio_chmap.c.14.o', 'audio/out/ao_coreaudio_exclusive.c.14.o', 'audio/out/ao_coreaudio_properties.c.14.o', 'audio/out/ao_coreaudio_utils.c.14.o', 'audio/out/ao_null.c.14.o', 'audio/out/ao_pcm.c.14.o', 'audio/out/pull.c.14.o', 'audio/out/push.c.14.o', 'common/av_common.c.14.o', 'common/av_log.c.14.o', 'common/codecs.c.14.o', 'common/common.c.14.o', 'common/tags.c.14.o', 'common/msg.c.14.o', 'common/playlist.c.14.o', 'common/version.c.14.o', 'demux/codec_tags.c.14.o', 'demux/cue.c.14.o', 'demux/demux.c.14.o', 'demux/demux_cue.c.14.o', 'demux/demux_disc.c.14.o', 'demux/demux_edl.c.14.o', 'demux/demux_lavf.c.14.o', 'demux/demux_mf.c.14.o', 'demux/demux_mkv.c.14.o', 'demux/demux_mkv_timeline.c.14.o', 'demux/demux_null.c.14.o', 'demux/demux_playlist.c.14.o', 'demux/demux_raw.c.14.o', 'demux/demux_rar.c.14.o', 'demux/demux_timeline.c.14.o', 'demux/demux_tv.c.14.o', 'demux/ebml.c.14.o', 'demux/packet.c.14.o', 'demux/timeline.c.14.o', 'input/cmd_list.c.14.o', 'input/cmd_parse.c.14.o', 'input/event.c.14.o', 'input/input.c.14.o', 'input/ipc.c.14.o', 'input/ipc-unix.c.14.o', 'input/keycodes.c.14.o', 'misc/bstr.c.14.o', 'misc/charset_conv.c.14.o', 'misc/dispatch.c.14.o', 'misc/json.c.14.o', 'misc/ring.c.14.o', 'misc/rendezvous.c.14.o', 'options/m_config.c.14.o', 'options/m_option.c.14.o', 'options/m_property.c.14.o', 'options/options.c.14.o', 'options/parse_commandline.c.14.o', 'options/parse_configfile.c.14.o', 'options/path.c.14.o', 'player/audio.c.14.o', 'player/client.c.14.o', 'player/command.c.14.o', 'player/configfiles.c.14.o', 'player/external_files.c.14.o', 'player/loadfile.c.14.o', 'player/main.c.14.o', 'player/misc.c.14.o', 'player/lavfi.c.14.o', 'player/lua.c.14.o', 'player/osd.c.14.o', 'player/playloop.c.14.o', 'player/screenshot.c.14.o', 'player/scripting.c.14.o', 'player/sub.c.14.o', 'player/video.c.14.o', 'stream/cache.c.14.o', 'stream/cache_file.c.14.o', 'stream/cookies.c.14.o', 'stream/frequencies.c.14.o', 'stream/rar.c.14.o', 'stream/stream.c.14.o', 'stream/stream_avdevice.c.14.o', 'stream/stream_edl.c.14.o', 'stream/stream_file.c.14.o', 'stream/stream_lavf.c.14.o', 'stream/stream_memory.c.14.o', 'stream/stream_mf.c.14.o', 'stream/stream_null.c.14.o', 'stream/stream_rar.c.14.o', 'stream/stream_tv.c.14.o', 'stream/tv.c.14.o', 'stream/tvi_dummy.c.14.o', 'sub/ass_mp.c.14.o', 'sub/dec_sub.c.14.o', 'sub/draw_bmp.c.14.o', 'sub/img_convert.c.14.o', 'sub/lavc_conv.c.14.o', 'sub/osd.c.14.o', 'sub/osd_libass.c.14.o', 'sub/sd_ass.c.14.o', 'sub/sd_lavc.c.14.o', 'video/csputils.c.14.o', 'video/fmt-conversion.c.14.o', 'video/image_writer.c.14.o', 'video/img_format.c.14.o', 'video/mp_image.c.14.o', 'video/mp_image_pool.c.14.o', 'video/sws_utils.c.14.o', 'video/decode/dec_video.c.14.o', 'video/decode/vd_lavc.c.14.o', 'video/decode/videotoolbox.c.14.o', 'video/filter/vf.c.14.o', 'video/filter/vf_buffer.c.14.o', 'video/filter/vf_crop.c.14.o', 'video/filter/vf_dlopen.c.14.o', 'video/filter/vf_dsize.c.14.o', 'video/filter/vf_eq.c.14.o', 'video/filter/vf_expand.c.14.o', 'video/filter/vf_flip.c.14.o', 'video/filter/vf_format.c.14.o', 'video/filter/vf_gradfun.c.14.o', 'video/filter/vf_lavfi.c.14.o', 'video/filter/vf_mirror.c.14.o', 'video/filter/vf_noformat.c.14.o', 'video/filter/vf_pullup.c.14.o', 'video/filter/vf_rotate.c.14.o', 'video/filter/vf_scale.c.14.o', 'video/filter/vf_stereo3d.c.14.o', 'video/filter/vf_sub.c.14.o', 'video/filter/vf_yadif.c.14.o', 'video/out/aspect.c.14.o', 'video/out/bitmap_packer.c.14.o', 'video/out/dither.c.14.o', 'video/out/filter_kernels.c.14.o', 'video/out/vo.c.14.o', 'video/out/vo_image.c.14.o', 'video/out/vo_null.c.14.o', 'video/out/win_state.c.14.o', 'osdep/terminal-unix.c.14.o', 'osdep/io.c.14.o', 'osdep/timer.c.14.o', 'osdep/timer-darwin.c.14.o', 'osdep/threads.c.14.o', 'osdep/semaphore_osx.c.14.o', 'osdep/subprocess.c.14.o', 'osdep/subprocess-posix.c.14.o', 'osdep/path-unix.c.14.o', 'ta/ta.c.14.o', 'ta/ta_talloc.c.14.o', 'ta/ta_utils.c.14.o', '-o', '/private/tmp/mpv-20160606-13105-lfyjf1/mpv-0.17.0/build/mpv', '-framework', 'CoreFoundation', '-framework', 'CoreAudio', '-framework', 'AudioUnit', '-framework', 'AudioToolbox', '-framework', 'IOSurface', '-L/usr/local/Cellar/little-cms2/2.7/lib', '-L/usr/local/Cellar/lua/5.2.4_3/lib', '-L/usr/local/Cellar/ffmpeg/3.0.2/lib', '-L/usr/local/Cellar/ffmpeg/3.0.2/lib', '-L/usr/local/Cellar/ffmpeg/3.0.2/lib', '-L/usr/local/Cellar/ffmpeg/3.0.2/lib', '-L/usr/local/Cellar/libass/0.13.2/lib', '-llcms2', '-llua', '-lm', '-lz', '-lswresample', '-lavfilter', '-lavutil', '-lavcodec', '-lavformat', '-lswscale', '-lm', '-lavdevice', '-lass', '-liconv', '-ljpeg']

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Error: No such keg: /usr/local/Cellar/mpv

Setting up mpv
building file list ... done

sent 270 bytes  received 20 bytes  580.00 bytes/sec
total size is 14.98K  speedup is 51.64

What can I do? I'm new in Mac OSX.

**Comment by mrcotter** [comment]
It seems there was an error in relating to ffmpeg. Try follow the instructions in [https://git.io/brew-troubleshooting](https://git.io/brew-troubleshooting):
- Run `brew update && brew upgrade --all && brew cleanup`.
- Run `brew doctor` and fix all the warnings (outdated Xcode/CLT and unbrewed dylibs are very likely to cause problems).
- Check that Command Line Tools for Xcode (CLT) and/or Xcode are up to date.
- If things fail with permissions errors, check the permissions in /usr/local. If you’re unsure what to do, you can `sudo chown -R $(whoami) /usr/local`.

After that, try reinstall 'mpv' with the script provided. It should work.

**Comment by KiritoStudio** [comment]
Thank you very much, it worked.
