### ISSUE TITLE
请在 mpv/install.sh 中加上引号

### ISSUE THREAD

**Issue by bao3** [mrcotter/mrcotter_dotfiles#3]
在 

`MPVDIR=$( cd "$( "dirname" "${BASH_SOURCE[0]}" )" && pwd ) ` 中，请把 `dirname` 加上 `""` 引号

在 所有的 `$MPVDIR` 中都要加上` "" ` 引号 变成 ` "$MPVDIR" ` ，主要是针对的是路径中有空格的情况。

**Comment by mrcotter** [comment]
已更新安装脚本，谢谢提供改进意见
